// import Navbar from "./Components/Navbar";
// import Footer from "./Components/Footer";

// export default function RootLayout({ children }) {
//   return (
//     // <div
//     //  className={`page bg-site text-white bg-cover bg-no-repeat relative`}
//     // >
//     //   <Navbar />
//     //   <main>{children}</main>
//     //   <Footer />
//     // </div>
//     <html lang="en">
//       <body>
//         <Navbar />
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }

// export default Layout;

// import Navbar from "./Components/Navbar";
// import Footer from "./Components/Footer";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar />
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }
"use client";
import { AnimatePresence, motion } from "framer-motion";

import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import Transition from "./Components/Transition";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AnimatePresence mode="wait">
          <Navbar />
          {/* <Transition /> */}
          <motion.div className="h-full w-full">{children}</motion.div>
        </AnimatePresence>
        <Footer />
      </body>
    </html>
  );
}
